host:
	make -f host.mk host

csim:
	make -f firmware.mk csim

csynth: 
	make -f firmware.mk csynth

csynth-fused: 
	make -f firmware.mk csynth-fused

link:
	make -f firmware.mk link
	
link-fused:
	make -f firmware.mk link-fused
	
package:
	make -f firmware.mk package
